cacheFolder: ./.yarn/cache

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures:
  {
    os: ['current', 'linux'],
    cpu: ['current', 'x64'],
    libc: ['current', 'glibc', 'musl'],
  }
