name: Test of pull request main from other branch

on:
  pull_request:
    branches: main

jobs:
  Test-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        run: |
          yarn set version 4.1.0

      - name: Install dependencies
        run: yarn install

      - name: Test utility functions
        run: yarn run test

      - name: Build with yarn
        run: yarn run build
        env:
          VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
          VITE_KAKAO_CLIENT_ID: ${{ secrets.VITE_KAKAO_CLIENT_ID }}
          VITE_KAKAO_REDIRECT_URI: ${{ secrets.VITE_KAKAO_REDIRECT_URI }}
